import { defineCollection, z } from 'astro:content';

// One entry per photograph. Generated by scripts/extract_metadata.py,
// but you can also hand-author entries.
const photos = defineCollection({
  type: 'data',
  schema: z.object({
    // Path to the original, relative to /public — e.g. "/images/originals/2024-lisbon-01.jpg"
    src: z.string(),
    title: z.string().optional(),
    caption: z.string().optional(),
    // ISO date the photo was taken. Drives the timeline.
    date: z.coerce.date(),
    // Location for the map view. Omit for photos without coordinates.
    location: z
      .object({
        lat: z.number(),
        lng: z.number(),
        place: z.string().optional(),
      })
      .optional(),
    // Free-form tags and a single collection grouping.
    tags: z.array(z.string()).default([]),
    collection: z.string().optional(),
    // Intrinsic dimensions, used to reserve layout space and avoid reflow.
    width: z.number().optional(),
    height: z.number().optional(),
    // Selected EXIF, surfaced in the detail view.
    exif: z
      .object({
        camera: z.string().optional(),
        lens: z.string().optional(),
        focalLength: z.string().optional(),
        aperture: z.string().optional(),
        shutter: z.string().optional(),
        iso: z.number().optional(),
      })
      .optional(),
  }),
});

export const collections = { photos };
